from . import as_mrp_production
from . import as_machine
from . import as_product_category
from . import as_sales_order
from . import as_stock_picking
from . import as_contenedor
from . import as_product_template
from . import as_res_partner
from . import as_quality_views
from . import as_stock_move_line